<?xml version="1.0"?>
<package format="3">
  <name>tb3_cognitive</name>
  <version>0.1.0</version>
  <description>Capa cognitiva TB3: NLP, FSM, LangChain, Percepción visual</description>
  <maintainer email="juankibenitez57@gmail.com">juanks</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>tb3_msgs</depend>
  <depend>control_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>builtin_interfaces</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
